// <auto-generated />
using System;
using ApiGuarderia.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiGuarderia.Migrations
{
    [DbContext(typeof(ApiGuarderiaDbContext))]
    [Migration("20260227021151_Inicio1")]
    partial class Inicio1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiGuarderia.Models.AsignacionModels", b =>
                {
                    b.Property<int>("asignacion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("asignacion_id"));

                    b.Property<int>("cuidador_id")
                        .HasColumnType("int");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("fecha_asignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("nino_id")
                        .HasColumnType("int");

                    b.HasKey("asignacion_id");

                    b.HasIndex("cuidador_id");

                    b.HasIndex("nino_id");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("ApiGuarderia.Models.CuidadorModels", b =>
                {
                    b.Property<int>("cuidador_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cuidador_id"));

                    b.Property<string>("email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("especialidad")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("cuidador_id");

                    b.ToTable("Cuidadores");
                });

            modelBuilder.Entity("ApiGuarderia.Models.NinoModels", b =>
                {
                    b.Property<int>("nino_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nino_id"));

                    b.Property<string>("alergias")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("nino_id");

                    b.ToTable("Ninos");
                });

            modelBuilder.Entity("ApiGuarderia.Models.AsignacionModels", b =>
                {
                    b.HasOne("ApiGuarderia.Models.CuidadorModels", "Cuidador")
                        .WithMany()
                        .HasForeignKey("cuidador_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiGuarderia.Models.NinoModels", "Nino")
                        .WithMany()
                        .HasForeignKey("nino_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuidador");

                    b.Navigation("Nino");
                });
#pragma warning restore 612, 618
        }
    }
}
